version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
     - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ecommerce
      POSTGRES_PASSWORD: postgres
    volumes:
     - pgdata:/data/postgres
    networks:
     - ecommerce-mern
  frontend:
    #here we've to specify the location of our Makefile
    build: ./frontend/
    stdin_open: true
    #here we're mapping the exposed port i.e, 3000 to our machine port 3000.
    # so that we can test the application on our port 3000.
    ports: 
      - "3000:3000"
    networks:
      - ecommerce-mern
    volumes:
      - ./frontend/:/frontend
      - /app/node_modules
  server:
    # here we've to specify the location of our Makefile
    build: ./server/
    ports:
    # here we're mapping the exposed port i.e, 5000 to our machine port 5000.
    # so that we can test the application on our port 5000.
      - "4000:8000"
    networks:
      - ecommerce-mern
    volumes:
      - ./server/:/app
      - /app/node_modules
    depends_on:
      - db
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks: 
     - ecommerce-mern
networks:
  ecommerce-mern:
    driver: bridge
volumes:
  mongo-data:
    driver: local
  pgdata: {}