name: Docker Image

on:
  push:
    branches: [ "Develop" ]
  pull_request:
    branches: [ "Develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image client
      run: echo "${{ snecrets.DOCKERPW }}" | docker login -u "sabirlkhaloufi" --password-stdi
            docker build ./frontend -t sabirlkhaloufi/frontend:latest
            docker push sabirlkhaloufi/frontend:latest
      
            
